[package]
name = "inpm-impl"
version = "0.1.0"
authors = ["Liam Perlaki <lperlaki@icloud.com>"]
edition = "2018"



[lib]
proc-macro = true

[features]

embed=[]


[dependencies]
proc-macro-hack = "0.5"
proc-macro2 = "1"
syn="1"
quote="1"
walkdir="2.3"